### ISSUE TITLE
Fixed tests

### ISSUE THREAD

**Issue by Chrisissorry** [MortalFlesh/stringify#4]
Hi, cool project! Kinda fixed the tests in my fork: https://github.com/MortalFlesh/stringify/compare/master...Chrisissorry:feature/add-more-info-for-objects-fixed-tests

Let me know if you would require changes to accept it as a PR. 

Forked it cause I need any `DateTimeInterface` instance as a plain date string, e.g. `2018-08-11 20:15:00`. Guess that's not what you intend, right?

**Comment by MortalFlesh** [comment]
Hello,

thanks for this issue and the commit.

To be honest, I've totally forget about this library 🤣 I wanted to finish the PR and then I've been busy, so it stayed opened. So thank you for fixing it and remind me :+1: 

---
About the intention, yea the idea is to stringify the objects with the class name, etc. to allow better debugging/logging - not to create parsable string (_even though you can still parse it, if you want to ofc ..._).

But if you need to stringify a value of the object itself .. well .. I would probably want to know the reason for that, to better understand the need, because there is planty of different solutions..

For example you can have different function to do that explicitly `stringifyValue`, but I probably would not mix it in `stringify` function.

---
About the fix you've made - I would probably just change the line in the exception from `105` to `__LINE__ - 1` to be more resilent. But feel free to send the PR right away, we can work on details in the PR. :+1:

**Comment by Chrisissorry** [comment]
Alright, I'll open a PR then :-)

About why I actually use the library: In my project, I log changes to my model objects into a separate audit table. There are columns for before/after values of a property and who changed this object when. Those properties can have different types, mostly the ones supported by Doctrine. The column type itself is `varchar`. I found it very helpful to use Stringify instead of type casting everything. 

I guess the best solution for me would be to wrap your library into a utility class. This would allow me to act upon some additional requirements of mine.

**Comment by MortalFlesh** [comment]
Well from DDD point of view, I'd say, you should define a serialization for every model object, to be explicit what changed, sometimes only id would change (if you had immutable objects like events).

But generally as I understand the problem, you might want to compare values (objects) with complete stringified values - including a class name, because if you change for example `DateTime` to `DateTimeImmutable`, the value would be the same, but it is still a change in the model, you might want to audit.

But a wrapper library, could do exactly what you want :) Because just a stringify a value, its more technical thing, than a domain specific.

**Comment by Chrisissorry** [comment]
Actually, I use Doctrine and Doctrine Lifecycle Events. It's possible to retrieve a changeset in an EventListener. This comes in quite handy. For each changed property, I write a separate entry to the my log table. 

I agree that your proposed solution is superior to mine. It's just that I don't want to implement my own comparison logic to compare what's changed :-) 

Thanks for your thoughts on this and thanks for this helpful library :-)

**Comment by MortalFlesh** [comment]
You are welcome :+1:
